=== stealthyziko/KantoxStores/src/test/resources/articles.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:complexType name="rulesType">
        <xs:sequence>
            <xs:element name="rule" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="articleType">
        <xs:sequence>
            <xs:element name="code" type="xs:string"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="price" type="xs:decimal"/>
            <xs:element name="rules" type="rulesType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="articlesType">
        <xs:sequence>
            <xs:element name="article" type="articleType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="articles" type="articlesType"></xs:element>
</xs:schema>

=== stealthyziko/KantoxStores/src/main/resources/articles.xml
<?xml version="1.0"?>
<articles
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com articles.xsd">
    <article>
        <code>GR1</code>
        <name>Green tea</name>
        <price>3.11</price>
        <rule>OneGetTwo</rule>
    </article>
    <article>
        <code>SR1</code>
        <name>Strawberries</name>
        <price>5.00</price>
        <rule>ThreeFor0_9Price</rule>
    </article>
    <article>
        <code>CF1</code>
        <name>Coffee</name>
        <price>11.23</price>
        <rule>ThreeForTwoThirds</rule>
    </article>
</articles>

=== stealthyziko/KantoxStores/src/test/resources/articles.xml
<?xml version="1.0"?>
<articles
        xmlns="https://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://www.w3schools.com articles.xsd">
    <article>
        <code>GR1</code>
        <name>Green tea</name>
        <price>3.11</price>
        <rules>
            <rule>OneGetTwo</rule>
        </rules>
    </article>
    <article>
        <code>SR1</code>
        <name>Strawberries</name>
        <price>5.00</price>
        <rules>
            <rule>ThreeFor0_9Price</rule>
        </rules>
    </article>
    <article>
        <code>CF1</code>
        <name>Coffee</name>
        <price>11.23</price>
        <rules>
            <rule>ThreeForTwoThirds</rule>
        </rules>
    </article>
</articles>
